version: "3"
services:
  helloworld:
    build: .
    image: helloworld
    container_name: helloworld_container
    entrypoint: "python"
    command: "app.py"
    environment:
      - VALUE=random
    expose:
    - "5000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - helloworld
