service: we45-sls-workshop-xxe
provider:
  name: aws
  runtime: python3.7
  memorySize: 2048
  timeout: 20
  stage: dev
  region: us-west-2

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:*"
        - "s3:*"
      Resource:
        - "*"

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    usePipenv: false
    slim: true
    strip: false

functions:
  xxe:
    handler: handler.main
    timeout: 20
    events:
      - s3:
          bucket: we45-sls-xxe-${sls:instanceId}
          event: s3:ObjectCreated:*