apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: we-care
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: we-care
    spec:
      containers:
      - image: we45/wecare
        imagePullPolicy: IfNotPresent
        name: we-care
        ports:
        - containerPort: 80