apiVersion: v1
kind: Pod
metadata:
  name: ngflask-redis
  labels:
    app: ngflask-redis
spec:
  containers:
    - name: nginx
      image: nginx:1.11
      ports:
      - containerPort: 80
      volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: config-volume
    - name: redis
      image: redis
      ports:
      - containerPort: 6379
    - name: vulflask-redis
      image: abhaybhargav/vul_flask_redis
      imagePullPolicy: Always
      env:
        - name: REDIS_HOST
          value: 127.0.0.1
      ports:
      - containerPort: 5000
        name: vulflask-port
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
        items:
        - key: reverseproxy.conf
          path: reverseproxy.conf
