apiVersion: v1
kind: Secret
metadata:
  name: pgsql
  namespace: secret
type: Opaque
data:
  user: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2gvP3Y9ZFF3NHc5V2dYY1E=
  password: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2gvP3Y9ZFF3NHc5V2dYY1E=
  database: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2gvP3Y9ZFF3NHc5V2dYY1E=
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-creds
  namespace: secret
type: Opaque
data:
  email: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2gvP3Y9ZFF3NHc5V2dYY1E=
  password: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2gvP3Y9ZFF3NHc5V2dYY1E=
