version: "3"
services:
  helloworld:
    image: helloworld:latest
    expose:
    - "5000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - helloworld
